name: Build Zephyr Examples

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  ZEPHYRPROJECT: ${{ github.workspace }}/zephyrproject
  ZEPHYR_SDK_INSTALL_DIR: ${{ github.workspace }}/zephyrproject/sdk

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Generate the cache key
        run: |
          date +cache_key=${{ github.event.repository.name }}-zephyrproject-y%Y-w%W >>$GITHUB_ENV

      - name: Cache the Zephyr workspace
        id: cache-zephyrproject
        uses: actions/cache@v4
        with:
          path: ${{ env.ZEPHYRPROJECT }}
          key: ${{ env.cache_key }}

      - name: Clone the repository
        if: ${{ steps.cache-zephyrproject.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v5
        with:
          path: ${{ env.ZEPHYRPROJECT }}/${{ github.event.repository.name }}

      - name: Setup a new Zephyr workspace
        if: ${{ steps.cache-zephyrproject.outputs.cache-hit != 'true' }}
        run: |
          python -m venv ${ZEPHYRPROJECT}/.venv
          . ${ZEPHYRPROJECT}/.venv/bin/activate
          python -m pip install west ninja
          cd ${ZEPHYRPROJECT}
          west init --local ${{ github.event.repository.name }}
          west update
          west packages pip --install
          west sdk install --install-dir ${{ env.ZEPHYR_SDK_INSTALL_DIR }} --toolchains riscv64-zephyr-elf

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        soc_version: ["rtl_1_0", "rtl_1_1"]
        application: ["zephyr_imx219", "zephyr_imx219_dual", "zephyr_imx219_stacked"]
    steps:

      - name: Generate the cache key
        run: |
          date +cache_key=${{ github.event.repository.name }}-zephyrproject-y%Y-w%W >>$GITHUB_ENV

      - name: Restore the Zephyr workspace
        id: restore-zephyrproject
        uses: actions/cache@v4
        with:
          path: ${{ env.ZEPHYRPROJECT }}
          key: ${{ env.cache_key }}

      - name: Delete the outdated repository
        run: |
          rm -rf ${{ env.ZEPHYRPROJECT }}/${{ github.event.repository.name }}

      - name: Clone a recent version of the repository
        uses: actions/checkout@v5
        with:
          path: ${{ env.ZEPHYRPROJECT }}/${{ github.event.repository.name }}

      - name: Update the Zephyr workspace
        run: |
          . ${ZEPHYRPROJECT}/.venv/bin/activate
          cd ${ZEPHYRPROJECT}
          west update
          west zephyr-export
          west patch apply
          west config -l
          west list

      - name: Build the firmware samples
        run: |
          . ${ZEPHYRPROJECT}/.venv/bin/activate
          cd ${ZEPHYRPROJECT}/${{ github.event.repository.name }}/firmware/${{ matrix.application }}
          west build -b "tinyclunx33@rev2/${{ matrix.soc_version }}"
          cp build/zephyr/zephyr.elf ${ZEPHYRPROJECT}/tinyclunx33_${{ matrix.application }}_${{ matrix.soc_version }}_${{ steps.date.outputs.date }}_${{ github.sha }}.elf
          cp build/zephyr/zephyr.bin ${ZEPHYRPROJECT}/tinyclunx33_${{ matrix.application }}_${{ matrix.soc_version }}_${{ steps.date.outputs.date }}_${{ github.sha }}.bin

      - name: Upload the firmware files
        uses: actions/upload-artifact@v4
        with:
          name: tinyclunx33_zephyr_examples
          path: |
            ${ZEPHYRPROJECT}/tinyclunx33_*.bin
            ${ZEPHYRPROJECT}/tinyclunx33_*.elf
